doc-warnings: yes
test-warnings: no
strictness: veryhigh
max-line-length: 120
uses:
    - django
autodetect: yes
ignore-paths:
    - manage.py
    - tutorial/settings.py
    - tutorial/wsgi.py
ignore-patterns:
    - __init__\.py$